### PR TITLE
Renamed TextCharacterStyleTMPSynchronizer so file and class match name

### PR DESCRIPTION
**Pull request by nolimet**
Fix for #12

### CODE REVIEW

**Comment by Haruma-K** [comment]
Thanks for finding the bug!

This is a class name error, so I will correct the class name and merge.

**Comment by Haruma-K** [comment]
On second thought, I don't have permission to edit the branch.
I would like to have both the file name and the class name changed to TextMeshProUGUICharacterStyleTMPSynchronizer. Then I will merge it.

**Comment by nolimet** [comment]
Alrighty.~

**Comment by nolimet** [comment]
wouch found a second script with the same issue
Selectable Normal Color Setter

**Comment by Haruma-K** [comment]
Thanks again!
I will update now.

**Comment by nolimet** [comment]
No problem :)

**Pull request merged**
